#!/bin/bash
# =============================================================
# CGS Kitchen Display — Kiosk Update Script (Raspberry Pi Zero 2 W)
#
# ONE script for BOTH display units. The only difference between
# the Expo board and the Menu board is which repo it tracks, so
# the role is passed in as $1 (or read from /etc/celtech/role).
#
#   ./update.sh expo   -> tracks cgsKitchenExpo
#   ./update.sh menu   -> tracks cgsKitchenMenu
#
# Steps:
#   1. Hard-reset working copy to origin/main
#   2. Regenerate .env from /etc/celtech/env (Vite inlines
#      VITE_* at BUILD time, so env must exist before build)
#   3. npm ci && npm run build  (memory-guarded for 512MB RAM)
#
# The Zero 2 W has only 512MB RAM; a vue-tsc + Vite build can
# OOM. We require a swap file (see buildout) and cap Node heap.
# =============================================================

set -e

# ---- Resolve role -------------------------------------------
ROLE="${1:-}"
if [ -z "$ROLE" ] && [ -f /etc/celtech/role ]; then
    ROLE="$(cat /etc/celtech/role | tr -d '[:space:]')"
fi

case "$ROLE" in
    expo) APP_NAME="celtech-expo"; APP_LABEL="Expo Board" ;;
    menu) APP_NAME="celtech-menu"; APP_LABEL="Menu Board" ;;
    *)    echo "ERROR: role must be 'expo' or 'menu' (got '$ROLE'). Pass as arg or set /etc/celtech/role."; exit 1 ;;
esac

APP_DIR="/home/druid-mobile/$APP_NAME"
LOG_FILE="/home/druid-mobile/update.log"
ENV_FILE="/etc/celtech/env"
ENV_OUT="$APP_DIR/.env"
BRANCH="main"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [$ROLE] $1" | tee -a "$LOG_FILE"
}

log "-----------------------------------"
log "Starting CGS Kitchen $APP_LABEL software update"

if [ ! -d "$APP_DIR/.git" ]; then
    log "ERROR: $APP_DIR is not a git repository. Aborting."
    exit 1
fi

cd "$APP_DIR"

# ---- Wait for network (up to 30 seconds) -------------------
log "Waiting for network..."
WAIT=0
NETWORK_OK=1
until ping -c 1 -W 2 8.8.8.8 &>/dev/null; do
    WAIT=$((WAIT + 2))
    if [ $WAIT -ge 30 ]; then
        log "WARNING: No network after 30s. Skipping git update; will build existing checkout."
        NETWORK_OK=0
        break
    fi
    sleep 2
done

# ---- Pull latest --------------------------------------------
NEED_BUILD=0
if [ $NETWORK_OK -eq 1 ]; then
    log "Network ready after ${WAIT}s."
    log "Fetching from origin..."
    git fetch origin "$BRANCH" >> "$LOG_FILE" 2>&1

    LOCAL=$(git rev-parse HEAD)
    REMOTE=$(git rev-parse "origin/$BRANCH")

    if [ "$LOCAL" = "$REMOTE" ]; then
        if [ -n "$(git status --porcelain)" ]; then
            log "Local modifications detected, resetting to clean state..."
            git reset --hard "origin/$BRANCH" >> "$LOG_FILE" 2>&1
            NEED_BUILD=1
        fi
        log "Already up to date ($(git rev-parse --short HEAD))."
    else
        log "Update available: $(git rev-parse --short HEAD) -> $(git rev-parse --short origin/$BRANCH)"
        git reset --hard "origin/$BRANCH" >> "$LOG_FILE" 2>&1
        log "Updated to: $(git rev-parse --short HEAD)"
        NEED_BUILD=1
    fi
fi

# ---- Generate .env from environment file (always) ----------
# Both display apps need API base + key. Menu also accepts
# VITE_POLL_MS / VITE_BOARD_TITLE; Expo accepts VITE_POLL_MS.
# Unused vars are harmless.
log "Generating .env from $ENV_FILE..."
if [ ! -f "$ENV_FILE" ]; then
    log "WARNING: $ENV_FILE not found. .env will have empty values."
    API_BASE_URL=""
    API_KEY=""
    POLL_MS=""
    BOARD_TITLE=""
else
    set -a
    source "$ENV_FILE"
    set +a
fi

NEW_ENV="$(cat <<EOF
# Auto-generated by update.sh — do not edit manually.
# Values come from $ENV_FILE (role: $ROLE)
VITE_API_BASE_URL=${API_BASE_URL:-}
VITE_API_KEY=${API_KEY:-}
VITE_POLL_MS=${POLL_MS:-}
VITE_BOARD_TITLE=${BOARD_TITLE:-Menu}
EOF
)"

if [ ! -f "$ENV_OUT" ] || [ "$NEW_ENV" != "$(cat "$ENV_OUT")" ]; then
    echo "$NEW_ENV" > "$ENV_OUT"
    log ".env changed — build required."
    NEED_BUILD=1
else
    log ".env unchanged."
fi

# ---- Report key population ----------------------------------
if [ -n "${API_BASE_URL:-}" ]; then
    log "VITE_API_BASE_URL = ${API_BASE_URL}"
else
    log "WARNING: API_BASE_URL is empty — display cannot reach the backend."
fi
if [ -n "${API_KEY:-}" ]; then
    log "VITE_API_KEY present (${#API_KEY} chars)."
else
    log "WARNING: API_KEY is empty — /api/** calls will be rejected (401)."
fi

# ---- Build if needed (memory-guarded) -----------------------
if [ ! -d "$APP_DIR/dist" ]; then
    log "No dist/ present — build required."
    NEED_BUILD=1
fi

if [ $NEED_BUILD -eq 1 ]; then
    if [ $NETWORK_OK -eq 0 ] && [ ! -d "$APP_DIR/node_modules" ]; then
        log "ERROR: build needed but offline and node_modules missing. Keeping any existing dist/."
    else
        log "Building $APP_LABEL (memory-guarded for 512MB RAM)..."
        # Cap V8 heap so the build fails loudly instead of invoking
        # the OOM killer. Requires the swap file from the buildout.
        export NODE_OPTIONS="--max-old-space-size=384"
        if [ $NETWORK_OK -eq 1 ]; then
            npm ci >> "$LOG_FILE" 2>&1 || { log "ERROR: npm ci failed."; exit 1; }
        fi
        npm run build >> "$LOG_FILE" 2>&1 || { log "ERROR: npm run build failed (check swap is active: 'swapon --show')."; exit 1; }
        log "Build complete -> $APP_DIR/dist"
    fi
else
    log "No rebuild needed (no code or env change, dist/ present)."
fi

log "Update complete."
log "-----------------------------------"
exit 0
